//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowSure.Client.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrowSure.Client.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;Tasks&quot;,&quot;id&quot;:&quot;tasks&quot;,&quot;theme&quot;:&quot;green&quot;},{&quot;name&quot;:&quot;Assets&quot;,&quot;id&quot;:&quot;assets&quot;,&quot;theme&quot;:&quot;yellow&quot;},{&quot;name&quot;:&quot;Orders&quot;,&quot;id&quot;:&quot;orders&quot;,&quot;theme&quot;:&quot;blue&quot;},{&quot;name&quot;:&quot;Inventory&quot;,&quot;id&quot;:&quot;inventory&quot;,&quot;theme&quot;:&quot;red&quot;},{&quot;name&quot;:&quot;Settings&quot;,&quot;id&quot;:&quot;settings&quot;,&quot;theme&quot;:&quot;purple&quot;}].
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;48bb990e-c9ea-4d3e-b452-522263b72ac3&quot;,&quot;Type&quot;:{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Seed&quot;},&quot;TaskName&quot;:&quot;Seed Mint&quot;,&quot;Assignee&quot;:null,&quot;CreateDate&quot;:&quot;2018-06-04T02:26:16.5456371Z&quot;,&quot;DueOn&quot;:&quot;2018-06-04T02:26:16.5451357Z&quot;,&quot;AssigneeStatus&quot;:&quot;NotAccepted&quot;,&quot;Completed&quot;:false,&quot;CompletedDate&quot;:&quot;0001-01-01T00:00:00&quot;,&quot;Tags&quot;:[{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Seeding&quot;}],&quot;Location&quot;:&quot;Building 28&quot;},{&quot;Id&quot;:&quot;cf52919b-8156-442e-b538-ccfd67918b94&quot;,&quot;Type&quot;:{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Seed&quot;},&quot;TaskName&quot;:&quot;Seed Oregano&quot;,&quot;Assignee&quot;:null,&quot;CreateDate&quot;:&quot;2018-06-04T02:26:16.5466396Z&quot;,&quot;DueO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
    }
}
